// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDuhwddSYgZP-71Zfo4KUGThtGdBofCbIQ',
    appId: '1:745217816472:web:142a2970c158f6fa3f1ded',
    messagingSenderId: '745217816472',
    projectId: 'filter-coffeee-4493',
    authDomain: 'filter-coffeee-4493.firebaseapp.com',
    storageBucket: 'filter-coffeee-4493.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbVzteTecZf_VP7IRsL3eWVLl--twx-NM',
    appId: '1:745217816472:android:93b9be9f3f43f67b3f1ded',
    messagingSenderId: '745217816472',
    projectId: 'filter-coffeee-4493',
    storageBucket: 'filter-coffeee-4493.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzLTvuerbrSkrLnxL8tmvoFlfKfeEYoLM',
    appId: '1:745217816472:ios:c5eaaafce808ff4e3f1ded',
    messagingSenderId: '745217816472',
    projectId: 'filter-coffeee-4493',
    storageBucket: 'filter-coffeee-4493.appspot.com',
    iosBundleId: 'com.javapro.filtercoffee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzLTvuerbrSkrLnxL8tmvoFlfKfeEYoLM',
    appId: '1:745217816472:ios:c5eaaafce808ff4e3f1ded',
    messagingSenderId: '745217816472',
    projectId: 'filter-coffeee-4493',
    storageBucket: 'filter-coffeee-4493.appspot.com',
    iosBundleId: 'com.javapro.filtercoffee',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDuhwddSYgZP-71Zfo4KUGThtGdBofCbIQ',
    appId: '1:745217816472:web:0f34a8f8a57d6f0c3f1ded',
    messagingSenderId: '745217816472',
    projectId: 'filter-coffeee-4493',
    authDomain: 'filter-coffeee-4493.firebaseapp.com',
    storageBucket: 'filter-coffeee-4493.appspot.com',
  );
}
